### ISSUE TITLE
Compile: /usr/bin/ld can't find -lnvmchkpt

### ISSUE THREAD

**Issue by jimmypury** [RutgersCSSystems/CrossFS#1]
When I follow the steps in readme.md and exec the cmd, the lib can not be found in my VM.
If possible, could you please explain what the lib 'nvmchkpt' is?

by the way, git link in readme.md is outdated since owner's username is changed.

**Comment by ingerido** [comment]
libnvmchkpt is used to allocate buffer in PM. The instruction in the readme is based on the cloudlab instance as described. Since there's no PM there, you can remove libnvmchkpt if you want.

Also, I'm not sure I understand what do you mean by the "git link in readme.md is outdated since owner's username is changed". What link are you referring to? And what is the owner name and how does the owner name change matter our project? Please clarify. Thank you.

**Comment by jimmypury** [comment]
Sorry for the lack of detail. 
In<https://github.com/RutgersCSSystems/CrossFS#get-crossfs-source-code-on-github>, user or organization 'RutgersCSHeteroLab' does not exist.

**Comment by ingerido** [comment]
Ah, just notice that you mean the source code location. Yeah, we have changed our lab org name, sorry for not modifying that in the README in time. I have changed in the README
